name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: "Build and pack"
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install project dependencies
        run: npm ci

      - name: Build and create the installer
        run: npm run make -- --platform win32 --arch x64
