name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x
          cache: "yarn"

      - name: Install project dependencies
        run: yarn

      - name: Build and create the installer
        run: npm run make -- --platform win32 --arch x64
